# ===== BUILD STAGE =====
FROM gradle:8-jdk21 AS builder
WORKDIR /build
COPY . .
RUN gradle clean bootJar --no-daemon

# ===== RUNTIME STAGE (UNVERÄNDERT) =====
FROM amazoncorretto:25-alpine-jdk
LABEL version="1.0"
RUN apk add --no-cache tzdata fontconfig freetype font-noto ttf-liberation busybox-extras curl
ENV TZ=Europe/Vienna

COPY --from=builder /build/build/libs/backend.jar /jar/backend.jar

# JAR liegt im Volume!
ENTRYPOINT ["java","-Xms1024M","-Xmx2048M","-jar","/jar/backend.jar"]
