FROM node:22-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock ./frontend/
RUN cd frontend && yarn

COPY frontend ./frontend
RUN cd frontend && yarn build

FROM nginx:alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/http.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]